# Generated by Django 3.2.5 on 2021-09-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.CharField(default='user', max_length=255, unique=True),
        ),
    ]
