# Generated by Django 3.2.5 on 2021-09-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210926_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
